// Classes and structures being serialized

// Generated by ProtocolBuffer
// - a pure c# code generation implementation of protocol buffers
// Report bugs to: https://silentorbit.com/protobuf/

// DO NOT EDIT
// This file will be overwritten when CodeGenerator is run.
// To make custom modifications, edit the .proto file and add //:external before the message line
// then write the code and the changes in a separate file.
using System;
using System.Collections.Generic;

namespace Message
{
    public partial class MessageServantState
    {
        public int Code { get; set; }

    }

    public partial class MessageServantStateReply
    {
        public List<string> Id { get; set; }

        public List<int> State { get; set; }

        public List<int> Cpu { get; set; }

        public List<int> Memory { get; set; }

    }

    public partial class MessageState
    {
        public int Code { get; set; }

    }

    public partial class MessageStateReply
    {
        public int Code { get; set; }

    }

    public partial class MessagePipe
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Executor { get; set; }

        public bool MultipleInput { get; set; }

        public bool MultipleThread { get; set; }

        public List<string> Parameters { get; set; }

    }

    public partial class MessagePipeline
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public List<Message.MessagePipe> Pipes { get; set; }

    }

    public partial class MessageTaskDeliver
    {
        public string Id { get; set; }

        public List<string> Resources { get; set; }

        public List<string> Input { get; set; }

        public List<string> Servants { get; set; }

        public List<Message.MessagePipeline> Pipeline { get; set; }

    }

    public partial class MessageTaskDeliverReply
    {
        public string Taskid { get; set; }

        public int Code { get; set; }

        public string Message { get; set; }

    }

}
